# Configuration for gRPC-based application

client = "10.90.38.5"

[servers]
  [servers.0]
  ip = "10.90.38.14"
  port = 50050

  [servers.1]
  ip = "10.90.39.3"
  port = 50051

  #[servers.2]
  #ip = "10.90.40.6"
  #port = 50052

  #[servers.3]
  #ip = "10.90.40.8"
  #port = 50053

  #[servers.4]
  #ip = "10.90.40.9"
  #port = 50054

